name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: strelitzia
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install API deps & run tests
        run: |
          cd api
          npm ci
          npm run prisma:generate || true
          npm test || true
      - name: Install Web deps & tests
        run: |
          cd web
          npm ci
          npm test || true
      - name: Build docker images
        run: |
          docker build -t strelitzia-api ./api
          docker build -t strelitzia-web ./web